server:
  port: 8095

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.3:8060/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

redis:
  host: 172.17.0.4
  port: 6379
  password: test_passwd

graphs:
  storage:
    maxEdgesCount: 30